<?php declare(strict_types=1);


namespace swoft\opentracing\Mysql;

use InvalidArgumentException;
use Swoft\Bean\Annotation\Mapping\Bean;
use Swoft\Db\Query\Grammar\MySqlGrammar;
use Swoft\Db\Query\Grammar\Grammar;
use Swoft\Db\Query\Processor\MySqlProcessor;
use Swoft\Db\Query\Processor\Processor;
use Throwable;
use Swoft\Db\Connection\MySqlConnection as BaseMySqlConnection;

/**
 * Class MySqlConnection
 *
 * @Bean(scope=Bean::PROTOTYPE)
 *
 * @since 2.0
 */
class MySqlConnection extends BaseMySqlConnection
{
    public function select(string $query, array $bindings = [], bool $useReadPdo = true): array
    {
        return parent::select($query, $bindings, $useReadPdo); // TODO: Change the autogenerated stub
    }

    public function update(string $query, array $bindings = []): int
    {
        return parent::update($query, $bindings); // TODO: Change the autogenerated stub
    }

    public function delete(string $query, array $bindings = []): int
    {
        return parent::delete($query, $bindings); // TODO: Change the autogenerated stub
    }
}
